In [15]:
from preparing import batch2train_data, load_voc
import torch
from torch import nn
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
import random

In [16]:
data, Vocabulary = load_voc()

## Подготовка данных, для использования в модели


In [17]:
inp, lenghts, target, mask, max_target_len = batch2train_data([random.choice(data) for _ in range(2)])

In [18]:
inp.size()

torch.Size([24, 2])

In [19]:
target.size()

torch.Size([35, 2])

In [20]:
max_target_len

35

# Encoder

In [21]:
EMBEDDING_SIZE = 128

In [8]:
class Encoder(nn.Module):
    def __init__(self, embedding):
        super(Encoder, self).__init__()

        self.embedding = embedding
        self.gru = nn.GRU(EMBEDDING_SIZE, EMBEDDING_SIZE, num_layers=2,
                          dropout=0.4, bidirectional=True)

    def forward(self, input_seq, length, hidden=None):

        embed = embedding(input_seq)
        packed = pack_padded_sequence(embed, length)

        out, hidden = self.gru(packed, hidden)

        

In [9]:
embedding = nn.Embedding(Vocabulary.num_words, 128)

In [10]:
inp

tensor([[ 141,   76],
        [ 850, 2162],
        [  31,    4],
        [  92,    2],
        [5456,    0],
        [2735,    0],
        [2345,    0],
        [   4,    0],
        [7795,    0],
        [   2,    0]])

In [11]:
emb = embedding(inp)

In [12]:
emb

tensor([[[ 7.6495e-01, -7.9846e-01,  9.7364e-01,  2.0671e-01,  8.4591e-01,
          -2.3702e-01, -2.5182e-01, -3.5553e-01,  1.3117e+00,  7.4894e-01,
           4.8421e-01,  1.9481e+00],
         [-1.6844e+00,  2.8501e-01, -4.8173e-02, -1.2089e+00,  9.3491e-01,
          -1.5844e+00, -1.1133e-01, -3.5574e-01, -8.2981e-02,  5.8434e-01,
          -8.7333e-01,  2.7022e-01]],

        [[ 9.8881e-01, -2.1259e+00,  6.6027e-01, -1.4813e+00, -1.5786e-02,
          -9.7524e-01, -6.3703e-01, -5.7956e-01,  2.1022e+00,  2.0898e+00,
           6.1655e-01, -1.5544e-01],
         [-1.2701e+00, -2.5434e-01,  1.3117e+00, -2.1920e+00,  6.8146e-01,
           1.2522e-01, -4.8375e-01,  2.2123e+00,  6.9924e-01,  7.2910e-01,
           1.6325e-01,  1.3102e+00]],

        [[ 1.5886e+00, -1.0834e+00, -8.6062e-01,  5.9398e-01, -4.6124e-01,
          -7.5954e-02, -3.0960e-01,  1.3596e+00, -2.6842e-01, -5.9845e-01,
          -1.8842e-01,  5.8307e-01],
         [-9.6691e-01,  1.2917e+00,  4.0011e-01,  7.1057e-01,

In [13]:
lenghts

tensor([10,  4])

In [44]:
a = nn.utils.rnn.pack_padded_sequence(emb, lenghts)

In [50]:
a.data

tensor([[-0.2323, -0.4284,  1.5039, -1.2393,  0.0335,  0.1277,  0.3990,  2.3291,
         -1.1485,  1.0952,  0.9284, -2.3696],
        [ 0.1640, -0.8388, -1.2931, -0.7188, -0.5120, -0.5363,  0.4604, -1.0087,
          0.1091,  1.8481,  2.3347,  0.5019],
        [ 1.7727,  0.6450,  0.0584,  0.1305,  0.1873, -0.1868,  1.0666,  1.8425,
         -2.0361, -0.2729, -0.8967,  1.3933],
        [-0.2602,  1.6733,  0.9693,  0.4409,  0.0860, -0.0863,  1.1530,  0.4084,
          0.0098,  1.2563, -1.4813, -0.4833],
        [ 0.7899, -0.4167, -0.4157, -0.3190, -0.2022, -0.2899,  0.0514,  0.5048,
          0.7056, -0.4243, -0.2609, -1.3138],
        [ 1.5127, -0.3135,  1.2143,  0.4671, -0.9024,  0.0434,  1.3880, -0.2685,
         -0.6560,  0.3679,  0.1427, -1.1379],
        [-0.2076,  0.1346, -0.0425, -1.4533,  0.4038,  1.8281, -3.0003,  0.1724,
          2.0092,  1.3680,  0.2126,  0.8002],
        [ 1.1437,  0.0152,  0.4761,  0.8298,  1.1741, -0.1002, -0.4736, -1.7049,
          0.3177,  1.6033, -0.