In [2]:
import numpy as np

In [13]:
around = np.array([25, 27, 28, 29, 31, 33, 37, 39, 41, 42, 44, 45, 21, 22, 25, 30,
                   25, 31, 34, 33, 31, 27, 29, 30, 33, 31, 37, 41, 42, 43, 41, 42,
                   36, 33, 31, 38, 39, 41, 33, 31, 31])

In [4]:
around.sort()

In [5]:
around

array([21, 22, 25, 25, 25, 27, 27, 28, 29, 29, 30, 30, 31, 31, 31, 31, 31,
       31, 31, 33, 33, 33, 33, 33, 34, 36, 37, 37, 38, 39, 39, 41, 41, 41,
       41, 42, 42, 42, 43, 44, 45])

In [8]:
y = np.bincount(around)
ii = np.nonzero(y)[0]
print(zip(ii,y[ii]))

In [9]:
ii

array([21, 22, 25, 27, 28, 29, 30, 31, 33, 34, 36, 37, 38, 39, 41, 42, 43,
       44, 45])

In [17]:
len(around[(20 <= around) & (around < 30)])

10

In [18]:
len(around[(30 <= around) & (around < 40)])

21

In [19]:
len(around[(40 < around)])

10

In [20]:
len(around)

41

In [22]:
21 / 41

0.5121951219512195

In [23]:
np.median(around)

33.0

In [24]:
around.mean()

33.707317073170735

In [26]:
sum(around) / len(around)

33.707317073170735

In [27]:
np.var(around)

39.37775133848899

In [28]:
around

array([25, 27, 28, 29, 31, 33, 37, 39, 41, 42, 44, 45, 21, 22, 25, 30, 25,
       31, 34, 33, 31, 27, 29, 30, 33, 31, 37, 41, 42, 43, 41, 42, 36, 33,
       31, 38, 39, 41, 33, 31, 31])

$$ \frac{\sum^k_{i=1}{(xi - X)^2m_i}}{\sum{^k_{i=1}}} $$

In [29]:
X = sum(around) / len(around)

sum((xi - X)**2 for xi in around) / len(around)

39.377751338489006